E2E: Switch to node 4.7.3
Node 7 produces unreadable error messages in E2E tests like:
TypeError: Cannot read property 'trim' of undefined
      at sanitizeErrorMessage (/home/travis/.nvm/versions/node/v7.2.1/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)